apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app-name
spec:
  interval: 60m
  releaseName: app-name
  chart:
    spec:
      chart: onechart
      version: 0.34.0
      sourceRef:
        kind: HelmRepository
        name: onechart
        namespace: flux-system
      interval: 10m
  values:
    replicas: 1
    image:
      pullPolicy: IfNotPresent
      repository: ghcr.io/acrelec-cloud/scheduler-app-name
      tag: latest
    imagePullSecrets:
      - name: regcred
    containerPort: 80
    probe:
      enabled: true
      path: /
      settings:
        failureThreshold: 3
        initialDelaySeconds: 15
        periodSeconds: 30
        successThreshold: 1
        timeoutSeconds: 10
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 300m
        memory: 512Mi
    vars:
      NODE_ENV: production
