apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app-name
spec:
  values:
    image:
      tag: "${IMAGE_TAG}"
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/proxy-body-size: 64m
        nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      host: app-name.trunk.scheduler.sandbox.koji-dev.com
      ingressClassName: nginx
      tlsEnabled: true
    vars:
      CORS: 'https://trunk.scheduler.sandbox.koji-dev.com'
      DATABASE_URL: postgresql://admin:admin@database-ha:5432/database?sslmode=no-verify
      DATABASE_SYNCHRONIZE: 'true'
